server:
  port: 8105
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/super_partner?serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 2
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat
  # todo 邮箱配置
  mail:
    host: 127.0.0.1
    username: username
    password: password
  session:
    store-type: redis
    # 5小时过期
    timeout: 18000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: on
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDelete
      id-type: auto
campus:
  img: /img/
  job: "0 0 0 * * ? *"
# 阿里云对象存储  todo 需替换配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: xxxxx
      keysecret: xxxxxxx
      bucketname: xxxxxx
